title: Multi-Dimensional Games
author:
  name: multi-dimensional games
  email: 'stephen@thoughtstem.com'
metadata:
    description: We are a small but prolific game studio.

redirects:
    /internal: '/gravstrap-theme-versatile-internal-template[303]'
